-- migrate:up

-- Influencer identity lock: portrait-clone JSON read once from the base portrait, reused by every Gemini prompt.
ALTER TABLE public.influencers
  ADD COLUMN IF NOT EXISTS identity_lock jsonb;

-- The 12 B2B Brand styles (src/content/business/catalog/templatesB2b.ts). npm run db:seed:business keeps them in sync later.
INSERT INTO public.set_templates (id, product, name, description, cover_image, config, sort_order, is_active) VALUES
  ('executive-suite', 'brand', 'Executive Suite', 'A corner office with a city view.', '/images/business/us/influencer/brand/executive-suite-1.png', '{"lighting":"Soft overcast daylight from floor-to-ceiling windows, calm and premium.","defaults":{"wardrobe":"business_formal","poseEnergy":"confident_expert"},"locations":[{"id":"corner-office","label":"Corner office","direction":"Corner executive office with a walnut desk, leather chair and a softly blurred city skyline."}]}'::jsonb, 7, true),
  ('open-house', 'brand', 'Open House', 'The front porch of a home for sale.', '/images/business/us/influencer/brand/open-house-1.png', '{"lighting":"Warm late-afternoon sun, soft shadows, welcoming.","defaults":{"wardrobe":"smart_casual","poseEnergy":"warm_approachable"},"locations":[{"id":"front-porch","label":"Front porch","direction":"Front porch of a white suburban craftsman home with a navy door, potted boxwoods and a clean lawn, no signs."}]}'::jsonb, 8, true),
  ('law-office', 'brand', 'Law Office', 'Dark wood and shelves of law books.', '/images/business/us/influencer/brand/law-office-1.png', '{"lighting":"Soft window light with a warm desk lamp, serious and trustworthy.","defaults":{"wardrobe":"business_formal","poseEnergy":"confident_expert"},"locations":[{"id":"library-desk","label":"Library desk","direction":"Traditional law office with floor-to-ceiling dark wood shelves of leather-bound books and a green banker lamp, no readable spines."}]}'::jsonb, 9, true),
  ('holiday-season', 'brand', 'Holiday Season', 'Warm lights and a cozy festive room.', '/images/business/us/influencer/brand/holiday-season-1.png', '{"lighting":"Warm tungsten room light with soft bokeh from string lights.","defaults":{"wardrobe":"smart_casual","poseEnergy":"warm_approachable"},"locations":[{"id":"festive-living-room","label":"Festive living room","direction":"Cozy living room with a decorated pine tree, warm string lights and a knit throw, no text or logos."}]}'::jsonb, 10, true),
  ('boardroom', 'brand', 'Boardroom', 'A long table, ready for a big meeting.', '/images/business/us/influencer/brand/boardroom-1.png', '{"lighting":"Even soft daylight with gentle overhead fill, crisp corporate feel.","defaults":{"wardrobe":"business_formal","poseEnergy":"confident_expert"},"locations":[{"id":"glass-boardroom","label":"Glass boardroom","direction":"Modern boardroom with a long oak table, black mesh chairs and a glass wall, no screens with text."}]}'::jsonb, 11, true),
  ('conference-stage', 'brand', 'Conference Stage', 'Speaking on stage at an event.', '/images/business/us/influencer/brand/conference-stage-1.png', '{"lighting":"Warm stage spotlight from the front, dark audience area behind.","defaults":{"wardrobe":"business_formal","poseEnergy":"dynamic_candid"},"locations":[{"id":"keynote-stage","label":"Keynote stage","direction":"Conference stage with a dark backdrop and soft blue ambient light, blank screen, no text."}]}'::jsonb, 12, true),
  ('podcast-studio', 'brand', 'Podcast Studio', 'A mic, headphones and soft panels.', '/images/business/us/influencer/brand/podcast-studio-1.png', '{"lighting":"Warm practical light with a soft key from the side, moody and intimate.","defaults":{"wardrobe":"smart_casual","poseEnergy":"warm_approachable"},"locations":[{"id":"podcast-desk","label":"Podcast desk","direction":"Small podcast studio with a black boom-arm microphone, grey acoustic panels and a warm lamp, no logos."}]}'::jsonb, 13, true),
  ('coworking-space', 'brand', 'Coworking', 'A busy, bright shared workspace.', '/images/business/us/influencer/brand/coworking-space-1.png', '{"lighting":"Bright diffused daylight from skylights, fresh and energetic.","defaults":{"wardrobe":"smart_casual","poseEnergy":"dynamic_candid"},"locations":[{"id":"shared-table","label":"Shared table","direction":"Industrial coworking space with exposed brick, long shared tables, laptops and hanging plants, people far and blurred."}]}'::jsonb, 14, true),
  ('rooftop-terrace', 'brand', 'Rooftop Terrace', 'A city rooftop at golden hour.', '/images/business/us/influencer/brand/rooftop-terrace-1.png', '{"lighting":"Golden-hour backlight with warm rim light on the hair.","defaults":{"wardrobe":"smart_casual","poseEnergy":"warm_approachable"},"locations":[{"id":"city-rooftop","label":"City rooftop","direction":"Rooftop terrace with a glass railing, teak lounge furniture and a soft city skyline at sunset."}]}'::jsonb, 15, true),
  ('on-the-road', 'brand', 'On the Road', 'In the car, between two showings.', '/images/business/us/influencer/brand/on-the-road-1.png', '{"lighting":"Soft daylight through the windshield, natural and candid.","defaults":{"wardrobe":"smart_casual","poseEnergy":"dynamic_candid"},"locations":[{"id":"driver-seat","label":"Driver seat","direction":"Driver seat of a parked modern car with a tan leather interior, tree-lined street blurred through the window, no badges."}]}'::jsonb, 16, true),
  ('hotel-lobby', 'brand', 'Hotel Lobby', 'A grand lobby on a business trip.', '/images/business/us/influencer/brand/hotel-lobby-1.png', '{"lighting":"Warm ambient lobby light with soft brass reflections.","defaults":{"wardrobe":"business_formal","poseEnergy":"confident_expert"},"locations":[{"id":"marble-lobby","label":"Marble lobby","direction":"Luxury hotel lobby with cream marble floors, brass details and a velvet sofa, no readable signs."}]}'::jsonb, 17, true),
  ('networking-event', 'brand', 'Networking Event', 'An evening mixer with a drink in hand.', '/images/business/us/influencer/brand/networking-event-1.png', '{"lighting":"Warm evening ambient light with soft bokeh from pendant bulbs.","defaults":{"wardrobe":"business_formal","poseEnergy":"dynamic_candid"},"locations":[{"id":"evening-mixer","label":"Evening mixer","direction":"Upscale evening networking event in a loft with pendant lights, guests far and blurred, no logos."}]}'::jsonb, 18, true)
ON CONFLICT (id) DO NOTHING;

-- migrate:down

UPDATE public.set_templates SET is_active = false WHERE id IN ('executive-suite', 'open-house', 'law-office', 'holiday-season', 'boardroom', 'conference-stage', 'podcast-studio', 'coworking-space', 'rooftop-terrace', 'on-the-road', 'hotel-lobby', 'networking-event');

ALTER TABLE public.influencers
  DROP COLUMN IF EXISTS identity_lock;
