import { chromium } from 'playwright';
import { mkdirSync } from 'node:fs';
const OUT = process.env.E2E_OUT ?? '.data/e2e';
mkdirSync(OUT, { recursive: true });
const BASE = process.env.E2E_BASE_URL ?? 'http://localhost:3100';
const ROOT = `${process.cwd()}/public/images/business`;
const shot = (page, name) => page.screenshot({ path: `${OUT}/${name}.png`, fullPage: false });
const browser = await chromium.launch({ channel: 'chrome' });
const page = await browser.newPage({ viewport: { width: 1280, height: 900 } });
page.on('pageerror', (e) => console.log('PAGEERROR', e.message));
page.on('console', (m) => m.type() === 'error' && console.log('CONSOLE', m.text()));
const email = `e2e-${Date.now()}@example.com`;
await page.goto(`${BASE}/start/brand`);
await page.getByLabel('Email').fill(email);
await page.getByLabel('First name').fill('Mai');
await page.getByLabel('Business name').fill('Mai Realty');
await page.getByRole('button', { name: 'Real estate' }).click();
await shot(page, '1-account');
await page.getByRole('button', { name: 'Continue' }).click();
await page.getByText('A few things before we start').waitFor();
for (const cb of await page.locator('input[type=checkbox]').all()) await cb.check({ force: true });
await shot(page, '2-consent');
await page.getByRole('button', { name: 'Agree and continue' }).click();
await page.getByText('Add three selfies').waitFor();
const inputs = page.locator('input[type=file]');
for (let i = 0; i < 3; i++) await inputs.nth(i).setInputFiles(`${ROOT}/onboarding/selfie-good.png`);
await shot(page, '3-selfies');
await page.getByRole('button', { name: 'Continue' }).click();
await page.getByText('Pick your set').waitFor();
await page.getByRole('radio').first().click();
await shot(page, '4-set');
await page.getByRole('button', { name: 'Save my set' }).click();
await page.getByText('Create your 3 free photos').waitFor();
await page.getByRole('button', { name: 'Create my free photos' }).click();
await page.getByText('Your free photos').waitFor();
await page.waitForFunction(() => document.querySelectorAll('img[alt="Your free photo"]').length === 3, null, { timeout: 60000 });
await shot(page, '5-trial');
await page.getByRole('button', { name: 'Continue' }).click();
await page.getByText('Keep creating every month').waitFor();
await page.getByRole('button', { name: 'Choose Growth' }).click();
await page.getByText('Transfer memo').waitFor();
await shot(page, '6-checkout');
await page.getByRole('button', { name: /Simulate transfer/ }).click();
await page.getByText('Payment received').waitFor({ timeout: 20000 });
await page.getByRole('button', { name: 'Continue' }).click();
await page.waitForURL(/\/app\/brand/, { timeout: 20000 });
await page.getByText('Recent batches').waitFor({ timeout: 20000 });
await page.waitForTimeout(1500);
await shot(page, '7-dashboard');
console.log('E2E brand OK', email);
await browser.close();
