import { chromium } from 'playwright';
import { mkdirSync } from 'node:fs';
const OUT = process.env.E2E_OUT ?? '.data/e2e';
mkdirSync(OUT, { recursive: true });
import { execSync } from 'node:child_process';
const BASE = process.env.E2E_BASE_URL ?? 'http://localhost:3100';
const out = execSync(`DATABASE_URL="${process.env.E2E_DATABASE_URL ?? `postgres://${process.env.USER}@localhost:5432/next5_dev?sslmode=disable`}" npx tsx --env-file=.env.local scripts/dev-seed-business.ts demo-brand@next5.local brand`, { cwd: process.cwd() }).toString();
const link = out.match(/Sign in: (\S+)/)[1];
const browser = await chromium.launch({ channel: 'chrome' });
const page = await browser.newPage({ viewport: { width: 1280, height: 900 } });
page.on('pageerror', (e) => console.log('PAGEERROR', e.message));
await page.goto(link);
await page.getByText('Recent batches').waitFor({ timeout: 20000 });
await page.goto(`${BASE}/app/brand/billing`);
await page.getByRole('button', { name: /60 photos/ }).click();
await page.getByText('Transfer memo').waitFor();
await page.getByRole('button', { name: /Simulate transfer/ }).click();
await page.getByText('Payment received').waitFor({ timeout: 20000 });
await page.screenshot({ path: `${OUT}/topup-paid.png` });
await page.getByRole('button', { name: 'Continue' }).click();
await page.waitForTimeout(1500);
await page.screenshot({ path: `${OUT}/billing.png`, fullPage: true });
await page.goto(`${BASE}/app/brand/create?theme=market-update`);
await page.getByText('How many photos?').waitFor();
await page.getByRole('button', { name: /^8 photos · / }).click();
await page.getByRole('button', { name: /9:16/ }).click();
await page.waitForFunction(() => /Generate \d+ photos/.test(document.body.innerText), null, { timeout: 15000 });
await page.screenshot({ path: `${OUT}/create.png`, fullPage: true });
await page.getByRole('button', { name: /Generate \d+ photos/ }).click();
await page.waitForURL(/\/app\/brand\/batches\//);
await page.waitForFunction(() => /16 of 16 ready/.test(document.body.innerText), null, { timeout: 90000 });
await page.screenshot({ path: `${OUT}/batch.png` });
await page.locator('button[aria-label^="Open "]').first().click();
await page.waitForTimeout(800);
await page.screenshot({ path: `${OUT}/lightbox.png` });
await page.keyboard.press('Escape');
await page.locator('button[aria-label="Redo"]').first().click();
await page.getByRole('button', { name: 'Redo photo' }).click();
await page.waitForTimeout(1500);
await page.goto(`${BASE}/app/brand/library`);
await page.waitForTimeout(2500);
await page.screenshot({ path: `${OUT}/library.png` });
await page.goto(`${BASE}/app/brand/sets`);
await page.waitForTimeout(2000);
await page.screenshot({ path: `${OUT}/sets.png` });
console.log('E2E brand create OK');
await browser.close();
