import { chromium } from 'playwright';
import { mkdirSync } from 'node:fs';
const OUT = process.env.E2E_OUT ?? '.data/e2e';
mkdirSync(OUT, { recursive: true });
import { execSync } from 'node:child_process';
const BASE = process.env.E2E_BASE_URL ?? 'http://localhost:3100';
const out = execSync(`DATABASE_URL="${process.env.E2E_DATABASE_URL ?? `postgres://${process.env.USER}@localhost:5432/next5_dev?sslmode=disable`}" npx tsx --env-file=.env.local scripts/dev-seed-business.ts demo-brand@next5.local brand`, { cwd: process.cwd() }).toString();
const link = out.match(/Sign in: (\S+)/)[1];
const browser = await chromium.launch({ channel: 'chrome' });
const page = await browser.newPage({ viewport: { width: 1280, height: 900 } });
page.on('pageerror', (e) => console.log('PAGEERROR', e.message));
await page.goto(link);
await page.getByText('Recent batches').waitFor({ timeout: 20000 });
await page.goto(`${BASE}/app/brand/billing`);
await page.getByRole('button', { name: /^60 photos/ }).click();
await page.getByText('Transfer memo').waitFor();
await page.getByRole('button', { name: /Simulate transfer/ }).click();
await page.getByText('Payment received').waitFor({ timeout: 20000 });
await page.screenshot({ path: `${OUT}/topup-paid.png` });
await page.getByRole('button', { name: 'Continue' }).click();
await page.waitForTimeout(1500);
await page.screenshot({ path: `${OUT}/billing.png`, fullPage: true });
await page.goto(`${BASE}/app/brand/create?theme=market-update`);
await page.getByText('How many photos?').waitFor();
await page.getByRole('button', { name: /^8 photos · / }).click();
await page.getByRole('button', { name: /9:16/ }).click();
await page.waitForFunction(() => /Generate \d+ photos/.test(document.body.innerText), null, { timeout: 15000 });
await page.screenshot({ path: `${OUT}/create.png`, fullPage: true });
await page.getByRole('button', { name: /Generate \d+ photos/ }).click();
await page.waitForURL(/\/app\/brand\/batches\//);
await page.waitForFunction(() => /16 of 16 ready/.test(document.body.innerText), null, { timeout: 90000 });
await page.screenshot({ path: `${OUT}/batch.png` });
// Full view on a phone: a vertical feed, the score as a pill, details on tap.
const desktop = page.viewportSize();
await page.setViewportSize({ width: 390, height: 844 });
await page.locator('button[aria-label^="Open "]').nth(1).click();
const feed = page.getByRole('dialog', { name: 'Photos' });
await feed.waitFor();
await feed.getByText(/\b2 \/ \d+/).waitFor({ timeout: 10000 }); // opens on the photo she tapped
const pill = feed.getByRole('button', { name: /^(Score \d+|Post Kit)$/ });
await pill.waitFor({ timeout: 20000 });
await page.waitForTimeout(600);
await page.screenshot({ path: `${OUT}/feed-1-photo.png` });
await pill.click();
await page.getByRole('dialog', { name: 'About this photo' }).waitFor();
await page.waitForTimeout(500);
await page.screenshot({ path: `${OUT}/feed-2-details.png` });
await page.keyboard.press('Escape');
await page.getByRole('dialog', { name: 'About this photo' }).waitFor({ state: 'detached' });
// Scrolling down moves to the next photo, one per screen.
await feed.locator('div[tabindex="-1"]').evaluate((el) => el.scrollBy({ top: el.clientHeight }));
await feed.getByText(/\b3 \/ \d+/).waitFor({ timeout: 10000 });
await page.keyboard.press('ArrowUp');
await feed.getByText(/\b2 \/ \d+/).waitFor({ timeout: 10000 });
await page.getByRole('button', { name: 'Close' }).click();
await feed.waitFor({ state: 'detached' });
if (desktop) await page.setViewportSize(desktop);
await page.locator('button[aria-label="Redo"]').first().click();
await page.getByRole('button', { name: 'Redo photo' }).click();
await page.waitForTimeout(1500);
await page.goto(`${BASE}/app/brand/library`);
await page.waitForTimeout(2500);
await page.screenshot({ path: `${OUT}/library.png` });
await page.goto(`${BASE}/app/brand/sets`);
await page.waitForTimeout(2000);
await page.screenshot({ path: `${OUT}/sets.png` });
console.log('E2E brand create OK');
await browser.close();
