import { chromium } from 'playwright';
import { mkdirSync } from 'node:fs';
const OUT = process.env.E2E_OUT ?? '.data/e2e';
mkdirSync(OUT, { recursive: true });
const BASE = process.env.E2E_BASE_URL ?? 'http://localhost:3100';
const ROOT = `${process.cwd()}/public/images/business`;
const browser = await chromium.launch({ channel: 'chrome' });
const page = await browser.newPage({ viewport: { width: 390, height: 844 } });
page.on('pageerror', (e) => console.log('PAGEERROR', e.message));
const email = `e2e-shop-${Date.now()}@example.com`;
await page.goto(`${BASE}/start/shop`);
await page.getByLabel('Email').fill(email);
await page.getByLabel('First name').fill('Vy');
await page.getByRole('button', { name: 'Fashion' }).click();
await page.getByRole('button', { name: 'Continue' }).click();
await page.getByText('A few things before we start').waitFor();
for (const cb of await page.locator('input[type=checkbox]').all()) await cb.check({ force: true });
await page.getByRole('button', { name: 'Agree and continue' }).click();
await page.getByText('Who wears your products?').waitFor();
await page.getByRole('button', { name: /Studio model/ }).click();
await page.getByRole('radio').first().click();
await page.screenshot({ path: `${OUT}/shop-model.png` });
await page.getByRole('button', { name: 'Continue' }).click();
await page.getByText('Pick your scene').waitFor();
await page.getByRole('radio').nth(1).click();
await page.getByRole('button', { name: 'Add one by hand' }).click();
await page.locator('input[type=file]').first().setInputFiles(`${ROOT}/shop/slider/dress-before.png`);
await page.getByLabel('Product name').fill('Satin slip dress');
await page.getByLabel('Category').selectOption('dress');
await page.getByLabel('Colour').fill('Sage green');
await page.screenshot({ path: `${OUT}/shop-look.png`, fullPage: true });
await page.getByRole('button', { name: 'Continue' }).click();
await page.getByText('Create your 3 free photos').waitFor();
await page.getByRole('button', { name: 'Create my free photos' }).click();
await page.waitForFunction(() => document.querySelectorAll('img[alt="Your free photo"]').length === 3, null, { timeout: 60000 });
await page.screenshot({ path: `${OUT}/shop-trial.png` });
await page.getByRole('button', { name: 'Continue' }).click();
await page.getByText('Keep creating every month').waitFor();
await page.getByRole('button', { name: /Not now/ }).click();
await page.waitForURL(/\/app\/shop/, { timeout: 20000 });
await page.getByText('Recent batches').waitFor({ timeout: 20000 });
await page.waitForTimeout(1200);
await page.screenshot({ path: `${OUT}/shop-dashboard.png` });
console.log('E2E shop OK', email);
await browser.close();
