import { chromium } from 'playwright';
import { mkdirSync } from 'node:fs';
const OUT = process.env.E2E_OUT ?? '.data/e2e';
mkdirSync(OUT, { recursive: true });
import { execSync } from 'node:child_process';
const BASE = process.env.E2E_BASE_URL ?? 'http://localhost:3100';
const IMG = `${process.cwd()}/public/images/business/shop/slider`;
const email = `shop-app-${Date.now()}@next5.local`;
const out = execSync(`DATABASE_URL="${process.env.E2E_DATABASE_URL ?? `postgres://${process.env.USER}@localhost:5432/next5_dev?sslmode=disable`}" npx tsx --env-file=.env.local scripts/dev-seed-business.ts ${email} shop`, { cwd: process.cwd() }).toString();
const link = out.match(/Sign in: (\S+)/)[1];
const browser = await chromium.launch({ channel: 'chrome' });
const context = await browser.newContext({ viewport: { width: 1280, height: 900 }, acceptDownloads: true });
const page = await context.newPage();
page.on('pageerror', (e) => console.log('PAGEERROR', e.message));
await page.goto(link);
await page.getByText('Recent batches').waitFor({ timeout: 20000 });
await page.goto(`${BASE}/app/shop/products`);
await page.getByRole('button', { name: 'Add products' }).first().click();
await page.locator('input[type=file][multiple]').setInputFiles([`${IMG}/dress-before.png`, `${IMG}/set-before.png`, `${IMG}/bag-before.png`]);
const names = ['Satin slip dress', 'Cream knit set', 'Tan shoulder bag'];
const cats = ['dress', 'set', 'bag'];
for (let i = 0; i < 3; i++) {
  await page.getByLabel(`Product ${i + 1} name`).fill(names[i]);
  await page.getByLabel(`Product ${i + 1} category`).selectOption(cats[i]);
  await page.getByLabel(`Product ${i + 1} SKU`).fill(`SKU-${i + 1}`);
}
await page.screenshot({ path: `${OUT}/shop-add.png` });
await page.getByRole('button', { name: /Save 3 products/ }).click();
await page.getByText('3 products added').waitFor({ timeout: 20000 });
for (const n of names) await page.getByRole('button', { name: `Select ${n}` }).click();
await page.screenshot({ path: `${OUT}/shop-products.png` });
await page.getByRole('button', { name: 'Create photos' }).click();
await page.waitForURL(/\/app\/shop\/create/);
await page.waitForFunction(() => /Generate \d+ photos/.test(document.body.innerText), null, { timeout: 20000 });
await page.screenshot({ path: `${OUT}/shop-create.png`, fullPage: true });
await page.getByRole('button', { name: /Generate \d+ photos/ }).click();
await page.waitForURL(/\/app\/shop\/batches\//);
await page.waitForFunction(() => /(\d+) of \1 ready/.test(document.body.innerText), null, { timeout: 90000 });
await page.waitForTimeout(1500);
await page.screenshot({ path: `${OUT}/shop-batch.png`, fullPage: true });
await page.locator('button[aria-label^="Open Satin slip dress"]').first().click();
await page.waitForTimeout(800);
await page.screenshot({ path: `${OUT}/shop-compare.png` });
await page.keyboard.press('Escape');
await page.locator('button[aria-label="Redo"]').first().click();
await page.getByRole('button', { name: 'Doesn’t match product' }).waitFor();
await page.getByRole('button', { name: 'Redo photo' }).click();
await page.getByText(/Redoing your photo/).waitFor({ timeout: 10000 });
const [download] = await Promise.all([page.waitForEvent('download', { timeout: 30000 }), page.getByRole('button', { name: 'Zip' }).first().click()]);
console.log('zip:', download.suggestedFilename());
console.log('E2E shop app OK', email);
await browser.close();
