import { NextResponse, type NextRequest } from 'next/server';
import { adminRoute } from '../../../../../src/server/admin/route';
import { HttpError } from '../../../../../src/server/http';
import { parseZillowUrl } from '../../../../../src/lib/listingPhotos';
import { APIFY_API, apifyCall, type ApifyRow } from '../../../../../src/server/apify/client';
import { getZillowRun, getZillowRows, isZillowImportMock, startZillowRun } from '../../../../../src/server/listings/zillowApify';
import { normalizeZillowRow } from '../../../../../src/server/listings/zillowNormalize';
import { eligibleAngles, type ListingFacts } from '../../../../../src/server/labs/slideshowCopy';
import { prisma } from '../../../../../src/lib/db';

// The Apify Zillow actor can take up to 90 s; give ourselves margin.
export const maxDuration = 130;

const POLL_INTERVAL_MS = 4_000;
const MAX_WAIT_MS = 120_000;

type Body = { url?: string; maxPhotos?: number };

const wait = (ms: number) => new Promise((r) => setTimeout(r, ms));

const pollUntilDone = async (runId: string): Promise<{ rows: ApifyRow[]; costUsd?: number }> => {
  const deadline = Date.now() + MAX_WAIT_MS;
  while (Date.now() < deadline) {
    await wait(POLL_INTERVAL_MS);
    const run = await getZillowRun(runId);
    if (run.status === 'failed') throw new HttpError(502, 'zillow_scrape_failed', 'The Zillow scrape failed. Try again.');
    if (run.status === 'succeeded' && run.datasetId) {
      const rows = isZillowImportMock()
        ? await getZillowRows(run.datasetId)
        : await apifyCall<ApifyRow[]>(`${APIFY_API}/datasets/${run.datasetId}/items?clean=1&format=json`);
      return { rows, costUsd: run.costUsd };
    }
  }
  throw new HttpError(504, 'zillow_scrape_timeout', 'Zillow scrape timed out. Try again.');
};

/**
 * POST /api/admin/blitz/zillow-scrape
 * Body: { url: string; maxPhotos?: number }
 * Returns: { runId, candidates, facts, angles, cached }
 *
 * - Checks DB for an existing run with the same zpid first (cache hit → instant).
 * - On a cache miss: runs Apify, saves result to blitz_listing_runs, returns runId.
 * - Stats recorded: scrapeDurationMs, apifyCostUsdMicros.
 */
export const POST = adminRoute(async (req: NextRequest) => {
  const body = (await req.json()) as Body;
  const rawUrl = body.url?.trim() ?? '';
  const maxPhotos = typeof body.maxPhotos === 'number' && body.maxPhotos > 0 ? body.maxPhotos : Infinity;

  const link = parseZillowUrl(rawUrl);
  if (!link) throw new HttpError(400, 'invalid_zillow_url', 'Open the home on Zillow, then copy that link.');

  // ── Cache check ────────────────────────────────────────────────────────────
  const existing = await prisma.blitzListingRun.findFirst({
    where: { zpid: link.zpid },
    orderBy: { createdAt: 'desc' },
  });

  if (existing) {
    const candidates = (existing.candidates as { id: string; url: string; thumbUrl: string; width?: number; height?: number }[])
      .slice(0, isFinite(maxPhotos) ? maxPhotos : undefined);
    return NextResponse.json({
      runId: existing.id,
      candidates,
      facts: existing.facts,
      angles: existing.angles,
      cached: true,
      // Restore previous selection if any
      selectedIds: existing.selectedIds,
      photoTags: existing.photoTags,
    });
  }

  // ── Cache miss: scrape Apify ────────────────────────────────────────────────
  const scrapeStart = Date.now();
  const { runId: apifyRunId } = await startZillowRun(link.url, link.zpid, null);
  const { rows, costUsd } = await pollUntilDone(apifyRunId);
  const scrapeDurationMs = Date.now() - scrapeStart;

  const listing = normalizeZillowRow(rows[0]);
  if (!listing) throw new HttpError(502, 'zillow_no_data', 'No data came back from Zillow. Try again.');

  const facts: ListingFacts = {
    address: listing.address?.full ?? null,
    city: listing.address?.city ?? null,
    state: listing.address?.state ?? null,
    priceUsd: listing.priceCents !== null ? listing.priceCents / 100 : null,
    beds: listing.beds,
    baths: listing.baths,
    sqft: listing.sqft,
    status: listing.status,
    daysOnMarket: listing.daysOnMarket,
    onMarketDate: listing.onMarketDate,
    priceHistory: listing.priceHistory,
    isOpenHouse: listing.isOpenHouse,
    description: listing.description,
  };

  const allCandidates = listing.candidates;
  const candidates = allCandidates.slice(0, isFinite(maxPhotos) ? maxPhotos : undefined);
  const angles = eligibleAngles(facts);

  // Persist to DB (id generated by @default(cuid()) in Prisma schema)
  const dbRun = await prisma.blitzListingRun.create({
    data: {
      zillowUrl: link.url,
      zpid: link.zpid,
      address: facts.address ?? null,
      facts: facts as object,
      candidates: allCandidates as object,
      angles: angles as object,
      scrapeDurationMs,
      apifyCostUsdMicros: costUsd !== undefined ? BigInt(Math.round(costUsd * 1_000_000)) : null,
    },
  });

  return NextResponse.json({
    runId: dbRun.id,
    candidates,
    facts,
    angles,
    cached: false,
    selectedIds: [],
    photoTags: [],
  });
});
